!                KB=# of vertical layers
      PARAMETER (KB=100,KBM1=KB-1)
      COMMON/BLKIND/ IINT,IEND,IPRINT
      COMMON/BLKT/TF(KB),T(KB),TB(KB),SF(KB),S(KB),SB(KB)
      COMMON/BLKU/UF(KB),U(KB),UB(KB),VF(KB),V(KB),VB(KB)
      COMMON/BLKQ/Q2F(KB),Q2(KB),Q2B(KB),Q2LF(KB),Q2L(KB),Q2LB(KB)
      COMMON/BLKR/RHO(KB),WT(KB)
      COMMON/BLKWU/WUSURF,WVSURF,WUBOT,WVBOT
      COMMON/BLKWT/WTSURF,WSSURF
      COMMON/BLKZ/Z(KB),ZZ(KB),DZ(KB),DZZ(KB),UMOL
      COMMON/BLKH/H,D,DT
      COMMON/BLKA/A(KB),C(KB),EE(KB),GG(KB)
      COMMON/BLKK/KM(KB),KH(KB),KQ(KB),L(KB),L0
      COMMON/MODEL/GM(KB),GH(KB),SM(KB),SH(KB),KN(KB),BOYGR(KB),&
        SPROD(KB),BPROD(KB),PROD(KB),DTEF(KB),STF(KB)
      REAL KAPPA,KN,KM,KH,KQ,L0,L
